global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']
# cadvisor exporter
  - job_name: 'consul-cadvisor-exporter'
    consul_sd_configs:
      - server: 'consul-server:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*cadvisor-exporter.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
# node exporter
  - job_name: 'consul-node-exporter'
    consul_sd_configs:
      - server: 'consul-server:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*node-exporter.*
        action: keep
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
# blackbox exporter
  - job_name: 'consul-blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    consul_sd_configs:
      - server: 'consul-server:8500'
        services: []
    relabel_configs:
     - source_labels: [__meta_consul_tags]
       regex: .*,healthcheck,.*
       action: keep
     - source_labels: [__meta_consul_tags]
       regex: .*,url:([^,]+),.*
       replacement: '${1}'
       target_label: __param_target
# blackbox exporter with multiply target
  - job_name: blackbox-http-check
    metrics_path: /probe
    params:
      module: [http_2xx]
    consul_sd_configs:
      - server: 'consul-server:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,prometheus-http-check,.*
        action: keep
      - source_labels: [__meta_consul_tags]
        regex: .*,team:([^,]+),.*
        replacement: '${1}'
        target_label: team
      - source_labels: [__param_module]
        target_label: job
      - source_labels: [__meta_consul_tags]
        regex: .*,http:([^,]+),.*
        replacement: '${1}'
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115